# === the basics ===
url: https://raine.is/
title: raine.is
email: me@kamila.is
permalink: /:categories/:title/
repository: anotherkamila/raine.is
github_username:  anotherkamila

# === defaults ===
defaults:
  - scope: {path: ""}
    values:
      layout: default
  - scope: {path: "talking"}
    values:
      layout: remark
  - scope: {path: "teaching"}
    values:
      layout: tocpost
  - scope: {path: "learning"}
    values:
      layout: tocpost

# === Build settings ===
excerpt_separator: <!--more-->
exclude: [Gemfile, Gemfile.lock]
include:
  - .well-known
plugins:
  - jekyll-sitemap
future: true
